### ISSUE TITLE
Makecall and Att transfer

### ISSUE THREAD

**Issue by OlegOLP** [Montesuma80/3cx-web-API#1]
Hello. We are 3CX partner and testing your API. 
Will you describe some moments?
1. Can't use make call. makecall/500/number/ and nothing happens. How use phone arg?
2. Can API get attended transfer event? User makes an attended transfer and we need to "tranfer" lead in CRM-system.

**Comment by Montesuma80** [comment]
makecall/from/to/Phone 

Phone could be 
Soft for Softphone 
Desk for Hardware Telefone 

Api can make att trans but not with the New Beta / Alpha 

Put the caller into the Park Position 
Make a New call 
Get the first Caller back from Park Position 
Then Transfer them to the second call.

Park/extension
Makecall/.....
Unpark/extension 
Atttans/extension

**Comment by Montesuma80** [comment]
attended transfer is fixed
3CX fixed there API in the newest version
