### ISSUE TITLE
Could not load file or assembly '3cxpscomcpp2

### ISSUE THREAD

**Issue by Jairuleizer** [Montesuma80/3cx-web-API#2]
I get the following error when running the application:

```
root@srv-pabx-02:~/3cx-web-API-master/bin/Debug/netcoreapp3.1# dotnet WebAPICore.dll 8888
System.IO.FileNotFoundException: Could not load file or assembly '3cxpscomcpp2, Version=2.0.0.0, Culture=neutral, PublicKeyToken=XXXXX'. The system cannot find the file specified.

File name: '3cxpscomcpp2, Version=2.0.0.0, Culture=neutral, PublicKeyToken=####'
   at WebAPI.Program.Bootstrap(String[] args)
   at WebAPI.Program.Main(String[] args) in /root/3cx-web-API-master/Program.cs:line 418
```

**Comment by RedTiger26** [comment]
Got the same error. Tried to change the path in the file WebAPICore.csproj to match the location installed. No luck.
Using 3CX Professional on Debian.

Any ideas how to fix?

**Comment by Pastis67** [comment]
Hello be sure that the path to 3cxpscomcpp2.dll is correct or maybe copy it to another location....

**Comment by RedTiger26** [comment]
Thanks for the fast reply. First when I tried to build, it failed not finding the DLL. After changing the path, it build successfully, but won't run. In addition I created a symlink for the correct INI file in the same directory as the executable as compiled.

**Comment by RedTiger26** [comment]
Thanks to some guys over at StackOverflow, I solved the problem: On Debian you need to remove the <Private>False</Private> entry in the WebAPI.csproj file. If you do that, building puts the DLL in the correct directory and everything works as expected.

https://stackoverflow.com/questions/65104434/c-sharp-dotnet-project-fails-to-run-assembly-file-not-found
