### ISSUE TITLE
Version issue Debian

### ISSUE THREAD

**Issue by mountIT** [Montesuma80/3cx-web-API#27]
Dear Ladies and Gentlemen,

I am getting an error while compiling.

CSC : error CS1705: Assembly '3cxpscomcpp2' with identity '3cxpscomcpp2, Version=2.0.0.0, Culture=neutral, PublicKeyToken=53c4927ce4749cb4' uses 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime' with identity 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [/root/3cx-web-API/WebAPICore.csproj]

To be honest I have searched a lot and have no clue how to solve it.
Could someone help?

Regards

**Comment by mountIT** [comment]
Solved. I had to install dotnet version 6.0 and set it to 6.0 in the WebAPICore.csproj

**Comment by bk-lg** [comment]
@mountIT please don't forget to close the ticket if you solved it.

**Comment by mountIT** [comment]
Solved. Thanks for your Help
