### ISSUE TITLE
Merge 2 calls

### ISSUE THREAD

**Issue by thornzz** [Montesuma80/3cx-web-API#3]
Hi,

Is there any possibility for merging 2 active calls? I have got one active call at CFD when other call is connected to pbx i will merge them. Any idea?

**Comment by Montesuma80** [comment]
Yes but only with the old V16 version. All new Versions have the same bug.
THe command for the API of me is: atttrans

**Comment by thornzz** [comment]
ok thank you. Will you update your project's status when this bug fixed?

**Comment by Montesuma80** [comment]
3CX fixed this Bug in there API in the newest version!

**Comment by thornzz** [comment]
Thanks for info.

**Comment by Montesuma80** [comment]
Can i ask you from where you are and do you use my API?
Only for my interest
-- 
Mit freundlichen Grüßen

Andreas Olenitzack



Am Do., 10. Dez. 2020 um 09:49 Uhr schrieb thornzz <notifications@github.com

**Comment by thornzz** [comment]
Sure. We are 3CX Platinium Distributor and im a software developer at this firm. Im developing 3rd party tools for 3CX. And using 3CX Api since 3-4 years. I dont use your api but i found your api while searching why 3cx joincall method not working. Good work. Not many developers for 3CX Api.

**Comment by Montesuma80** [comment]
3rd Party tools sounds nice. What Tools are you developing?

Mit freundlichen Grüßen

Andreas Olenitzack
IT-Operations

*Sanvartis GmbH*
Mercatorstraße 1b
47051 Duisburg

Tel.:      +49  2065 / 678 - 3416
E-Mail: andreas.olenitzack@sanvartis.de
Web:    www.sanvartis.de

Am Do., 10. Dez. 2020 um 10:08 Uhr schrieb thornzz <notifications@github.com

**Comment by thornzz** [comment]
We are developing custom tools for Customers need, Crm integrations, Auto Dialer, Predictive Dialers, Call Flow Applications etc. There is no limit :) Our slogan is what you need we can develop. And we are developing custom Report tool. This will be a product.

**Comment by Montesuma80** [comment]
Thanks, we need a tool to manage queue Agents (add to queue, remove from
queue, Show status of queue member)



-- 

-- 
Mit freundlichen Grüßen

Andreas Olenitzack




thornzz <notifications@github.com> schrieb am Fr., 11. Dez. 2020, 19:03:

**Comment by thornzz** [comment]
Sure we can do it. Here link an example tool that we have made. We can handle queue operations as well.
http://extmngr.buluttel.com
