### ISSUE TITLE
Доработка и мобификации под заказ

### ISSUE THREAD

**Issue by ITUnfallen** [Montesuma80/3cx-web-API#4]
Как связаться по вопросу доработки и некоторых модификаций?

**Comment by Montesuma80** [comment]
1. Please write in english or german
2. you can send me an Email: andreas.olenitzack@sanvartis.de
-- 
Mit freundlichen Grüßen

Andreas Olenitzack
Marderweg 24
45892 Gelsenkirchen

Telefon: 0049 (0) 209 36 69 99 89
Mobil:   0049 (0) 176 /  55 14 18 35


Am Do., 4. März 2021 um 02:36 Uhr schrieb ITUnfallen <
notifications@github.com>:

**Comment by Montesuma80** [comment]
closed
