### ISSUE TITLE
can't access from IP addresses other than the server IP address

### ISSUE THREAD

**Issue by SpaceEggs** [Montesuma80/3cx-web-API#9]
3CX Version: V18 Update1 Windows Version

I just can access the API in 3CX Server, but I can't access with other IPs.

I checked the firewall settings and no API ports are blocked

**Comment by Montesuma80** [comment]
Look at /etc/nftables.conf 
There you need to open the Port

**Comment by Montesuma80** [comment]
Sorry i did not read that you are using the Windows Version.
1. you need to start the API as Admin
2. you need to open the port in the Firewall (Windows or Antivirus Firewall)

But for bedder performance (3cx and API) use the Linux version

**Comment by SpaceEggs** [comment]
Thanks for your reply.

It's working after i disable firewall.
